spring:
  application:
    name: betnetix
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/betnetix}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:142536}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
